### ISSUE TITLE
Stateofdev.ma points to wrong location

### ISSUE THREAD

**Issue by MohcineDev** [geeksblabla/awesome-morocco#210]
I noticed that [stateofdev.ma](https://github.com/geeksblabla//awesome-morocco) link in the website footer is pointing to an incorrect location.

    Current Link: https://github.com/geeksblabla//awesome-morocco
    Expected Link: https://stateofdev.ma/

**Comment by zakarialaoui10** [comment]
@yjose 
@soub4i 

https://github.com/geeksblabla/awesome-morocco/pull/213

**Comment by soub4i** [comment]
Fixed by https://github.com/geeksblabla/awesome-morocco/pull/213
Thanks @zakarialaoui10
